version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizr/node:4.0.0-dev
    user: node:node
    env_file:
      - .env
    command: sh -c "dsync /mount/LICENSE /var/www/html/LICENSE & dsync /mount/README.md /var/www/html/README.md"
    volumes:
      - ./library:/var/www/html
      - ./:/mount
    restart: unless-stopped
  examples:
    container_name: ${PROJECT_NAME}_examples
    image: openizr/node:4.0.0-dev
    user: node:node
    env_file:
      - .env
    ports:
      - "127.0.0.1:${EXAMPLES_PORT}:${EXAMPLES_PORT}"
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./examples:/var/www/html
      - ./library:/typescript-dev-kit
    restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.52.0/24
