version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizr/node:2.0.1-dev
    env_file:
      - .env
    command: sh -c "dsync /mount/LICENSE /var/www/html/LICENSE & dsync /mount/README.md /var/www/html/README.md"
    volumes:
      - ./library:/var/www/html
      - ./:/mount
    restart: unless-stopped
  playground:
    container_name: ${PROJECT_NAME}_playground
    image: openizr/node:2.0.1-dev
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PLAYGROUND_PORT}:${PLAYGROUND_PORT}"
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./playground:/var/www/html
      - ./library:/typescript-dev-kit
    restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
